name = "optim/account"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'optim/account'"

[repository]
user = "optim"
project = "account"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"

[[dependencies]]
name = "aiken-lang/sample"
version = "main"
source = "github"

[config]
